apiVersion: v1
kind: Pod
metadata: 
  name: sample-entrypoint
spec: 
  containers:
  - name: nginx-container
    image: nginx:latest
    command: ["/bin/sleep"] # ENTRYPOINT命令
    args: ["3600"] # CMD命令