apiVersion: v1
kind: Pod
metadata: 
  name: sample-pod2-fail
spec: 
  containers:
  - name: nginx-container
    image: nginx:latest
  - name: nginx-container2
    image: nginx:latest

  # pod内のIPアドレスは共有しているので、同じポート番号は利用できない